import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import useSWR from 'swr'

import getGovernanceData from '../lib/governanceData'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data, error } = useSWR('/', getGovernanceData)
  if (error) console.log(error)

  return (
    <div className={styles.container}>
      <Head>
        <title>Maker Governance Metrics</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className={styles.nav}>
        <div className={styles.logoContainer}>
          <Image src='/makerlogo.png' alt='Maker logo' width={42} height={30} />
          MakerDAO Governance Metrics
        </div>
      </nav>

      <main className={styles.main}>
        {error && (
          <div>
            There was an error trying to load the data, please refresh the site
          </div>
        )}
        {data ? (
          data.map((delegate, i) => <div key={i}>{delegate.voteDelegate}</div>)
        ) : (
          <div>Loading...</div>
        )}
      </main>

      <footer className={styles.footer}>Built by the GovAlpha Core Unit</footer>
    </div>
  )
}

export default Home
